#!/usr/bin/env python
# coding: utf-8

# Following the tutorial at https://emfollow.docs.ligo.org/userguide/tutorial/skymaps.html

import healpy as hp
import numpy as np
import os
import matplotlib.pyplot as plt

def get_map(event):
    basepath = basepath0+event+'/'
    for entry in os.listdir(basepath):
        if os.path.isfile(os.path.join(basepath, entry)):
            map_pdf = hp.read_map(basepath+entry, verbose=False)
            return map_pdf / (4 * np.pi / len(map_pdf)) # to get normalisation of posterior st p*d_Omega = 1

def coinc(hpx1, hpx2, event1, event2):
    N_points = len(hpx1) # value taken from Ashton et al 2018 code is 12*2**12
    d_Omega = 4 * np.pi / N_points
    prior = 1 / (4 * np.pi)
    add = hpx1 + hpx2
    hp.mollview(add)
    plt.title(str(event1)+" and "+str(event2))
    plt.savefig("data/joint_localisation_maps/"+str(event1)+"-"+str(event2)+"-add")
    mult = hpx1 * hpx2
    I_Omega = sum(mult) / prior * d_Omega
    exp = np.floor(np.log10(np.abs(I_Omega))).astype(int)
    hp.mollview(mult / prior * d_Omega)
    plt.title(str(event1)+" and "+str(event2)+": $I_\Omega = $"+str(I_Omega))
    plt.savefig("data/joint_localisation_maps/"+str(event1)+"-"+str(event2)+"-IOmega"+str(exp))
    return I_Omega

def shape_maps(map1, map2):
    nside = max(hp.pixelfunc.get_nside(map1), hp.pixelfunc.get_nside(map2))
    return hp.pixelfunc.ud_grade(map1,nside), hp.pixelfunc.ud_grade(map2,nside)

#basepath0 = 'data/sky_localisations/'
basepath0 = 'data/170817_events/'

events = []
for entry in os.listdir(basepath0):
    if os.path.isdir(os.path.join(basepath0, entry)):
        events.append(entry)

f = open("significant_coincidences.txt","w")

for idx1 in range(len(events)):
    for idx2 in range(idx1+1,len(events)):
        print(str(idx1)+"/"+str(len(events))+" : "+str(idx2)+"/"+str(len(events)))
        I_Omega = "may be different shapes"
#         try:
        if events[idx1] != events[idx2]:
            map1 = get_map(events[idx1])
            print("map1: "+events[idx1])
            map2 = get_map(events[idx2])
            print("map2: "+events[idx2])
            map1, map2 = shape_maps(map1,map2)
            I_Omega = coinc(map1, map2, events[idx1], events[idx2])
            #print("I_Omega for " + str(events[idx1]) + " and " + str(events[idx2]) + ": " + str(I_Omega))
            if I_Omega >= 1:
                f.write(str(events[idx1]) + " and " + str(events[idx2]) + ": " + str(I_Omega) + "\n")
        elif events[idx1] == events[idx2]:
            print("Tried comparing to itself")
#         except:
#             print(I_Omega)
#             pass

f.close()

# test one map with itself - should be >~1
idx = 1
map1 = get_map(events[0])
map2 = get_map(events[idx])
map1, map2 = shape_maps(map1,map2)
I_Omega = coinc(map1, map2, events[0], events[idx])
print("I_Omega: "+str(I_Omega))
